### ISSUE TITLE
Create stage environment

### ISSUE THREAD

**Issue by corylown** [pod4lib/aggregator#413]
We currently have only a production environment and need an environment to deploy and test work in progress.

**Comment by JohnMarkOckerbloom** [comment]
As we're nearing the end of the first iteration, I would be interested in knowing the status of this issue, including current progress, expected completion time, and roadblocks.

**Comment by anarchivist** [comment]
For reference, this is waiting on the following:

* [ ] sul-dlss/operations-tasks#2933 (presumed blocker)
* [ ] sul-dlss/operations-tasks#2928 (presumed blocker)
* [ ] sul-dlss/operations-tasks#2937 (important, but non blocking?(

**Comment by anarchivist** [comment]
The blocking issues are currently waiting on sul-dlss/puppet#7844 to be merged.

**Comment by anarchivist** [comment]
There's one remaining issue that I understand maybe a blocker (loading rvm for the application user, sul-dlss/operations-tasks#2937).

**Comment by corylown** [comment]
Leave open for now to track operations tasks.

**Comment by cbeer** [comment]
```
[Cory Lown](https://app.slack.com/team/URA3Z9H0F) [Today at 6:54 AM]
I did some digging into the issue we’re having on stage where the oai response gets cut off.
Some findings:
It’s not specific to the OAI implementation. Any request routed through the application and passenger suffers from the same problem, such as an ERB template with 2MB of HTML content.
Requests for large files in public/ do not have this issue.
The response does not always get cut off at the same place, but it’s roughly 170-200KB.
Prod does not have this issue. It will happily serve up 2MB files through the application and passenger with no issue.
I’m wondering if all the new Ubuntu VMs have the same issue, or maybe pod-stage is misconfigured somehow?
```

**Comment by corylown** [comment]
this is complete
